# Generated by Django 4.0.4 on 2022-06-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputAmenity',
            fields=[
                ('big_id', models.BigAutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('membership', models.CharField(max_length=400)),
                ('arrival_date', models.CharField(default='2022-01-01', max_length=100)),
                ('returns', models.IntegerField(default=0)),
                ('vip_level', models.IntegerField(default=0)),
                ('guests_count', models.IntegerField(default=1)),
                ('room_allocation', models.IntegerField(default=100)),
                ('fruit_amenity', models.CharField(blank=True, choices=[('Small fruit', 'Small fruit'), ('Presidential', 'Presidential'), ('Large fruit', 'Large fruit'), ('Midium fruit', 'Midium fruit')], max_length=200, null=True)),
                ('drink_amenity', models.CharField(blank=True, choices=[('Water', 'Water'), ('Red wine', 'Red wine'), ('Negroni', 'Negroni'), ('White wine', 'White wine'), ('Champagne', 'Champagne')], max_length=200, null=True)),
                ('dessert_amenity', models.CharField(blank=True, choices=[('Arab amenity', 'Arab amenity'), ('Baklava', 'Baklava'), ('Macaroons 4pcs', 'Macaroons 4pcs'), ('Chocolate truffle', 'Chocolate truffle'), ('Maamul', 'Maamul'), ('Macaroons 8pcs', 'Macaroons 8pcs')], max_length=200, null=True)),
                ('birthday_amenity', models.CharField(blank=True, choices=[('Congartulations', 'Congratulations'), ('Happy Birthday', 'Happy Birthday'), ('Happy Aniversary', 'Happy Amiversary')], max_length=200, null=True)),
                ('month', models.CharField(choices=[('September', 'September'), ('July', 'July'), ('April', 'April'), ('February', 'February'), ('March', 'March'), ('January', 'January'), ('June', 'June'), ('Octomber', 'Octomber'), ('August', 'August'), ('May', 'May'), ('December', 'December')], max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
