# Generated by Django 4.0.4 on 2022-05-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputAmenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('membership', models.CharField(max_length=400)),
                ('returns', models.IntegerField(default=0)),
                ('vip_level', models.IntegerField(default=0)),
                ('guests_count', models.IntegerField(default=0)),
                ('room_allocation', models.IntegerField()),
                ('fruit_amenity', models.CharField(choices=[('Large fruit', 'Large fruit'), ('Small fruit', 'Small fruit'), ('Midium fruit', 'Midium fruit'), ('Presidential', 'Presidential')], max_length=200)),
                ('drink_amenity', models.CharField(choices=[('Water', 'Water'), ('Red wine', 'Red wine'), ('Champagne', 'Champagne'), ('Negroni', 'Negroni'), ('White wine', 'White wine')], max_length=200)),
                ('dessert_amenity', models.CharField(choices=[('Maamul', 'Maamul'), ('Macaroons 8pcs', 'Macaroons 8pcs'), ('Baklava', 'Baklava'), ('Chocolate truffle', 'Chocolate truffle'), ('Macaroons 4pcs', 'Macaroons 4pcs'), ('Arab amenity', 'Arab amenity')], default=None, max_length=200)),
                ('birthday_amenity', models.CharField(choices=[('Happy Aniversary', 'Happy Amiversary'), ('Happy Birthday', 'Happy Birthday'), ('Congartulations', 'Congratulations')], default=None, max_length=200)),
            ],
        ),
    ]
