# Generated by Django 4.0.4 on 2022-05-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_inputamenity_birthday_amenity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InputAmenity',
        ),
    ]
