# Generated by Django 4.1 on 2022-08-08 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_inputamenity_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputamenity',
            name='birthday_amenity',
            field=models.CharField(blank=True, choices=[('Happy Birthday', 'Happy Birthday'), ('Congartulations', 'Congratulations'), ('Happy Aniversary', 'Happy Amiversary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='dessert_amenity',
            field=models.CharField(blank=True, choices=[('Chocolate truffle', 'Chocolate truffle'), ('Arab amenity', 'Arab amenity'), ('Baklava', 'Baklava'), ('Macaroons 4pcs', 'Macaroons 4pcs'), ('Maamul', 'Maamul'), ('Macaroons 8pcs', 'Macaroons 8pcs')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='drink_amenity',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Red wine', 'Red wine'), ('White wine', 'White wine'), ('Negroni', 'Negroni'), ('Champagne', 'Champagne')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='fruit_amenity',
            field=models.CharField(blank=True, choices=[('Large fruit', 'Large fruit'), ('Small fruit', 'Small fruit'), ('Presidential', 'Presidential'), ('Midium fruit', 'Midium fruit')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='month',
            field=models.CharField(choices=[('May', 'May'), ('September', 'September'), ('February', 'February'), ('June', 'June'), ('August', 'August'), ('December', 'December'), ('April', 'April'), ('March', 'March'), ('July', 'July'), ('January', 'January'), ('Octomber', 'Octomber')], max_length=300),
        ),
        migrations.CreateModel(
            name='LongStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_amenity', models.CharField(blank=True, choices=[('Water', 'Water'), ('Red wine', 'Red wine'), ('White wine', 'White wine'), ('Negroni', 'Negroni'), ('Champagne', 'Champagne')], max_length=200, null=True)),
                ('amenity', models.CharField(choices=[('Florentine', 'Florebntine'), ('Pistachio Finnacier', 'Pistachio Finnacier'), ('Macaroons', 'Macaroons')], max_length=200)),
                ('month', models.CharField(choices=[('May', 'May'), ('September', 'September'), ('February', 'February'), ('June', 'June'), ('August', 'August'), ('December', 'December'), ('April', 'April'), ('March', 'March'), ('July', 'July'), ('January', 'January'), ('Octomber', 'Octomber')], max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.inputamenity')),
            ],
        ),
    ]
