# Generated by Django 4.0.4 on 2022-05-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calc', '0003_delete_inputamenity'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputAmenity',
            fields=[
                ('big_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('membership', models.CharField(max_length=400)),
                ('returns', models.IntegerField()),
                ('vip_level', models.IntegerField()),
                ('guests_count', models.IntegerField()),
                ('room_allocation', models.IntegerField()),
                ('fruit_amenity', models.CharField(choices=[('Midium fruit', 'Midium fruit'), ('Large fruit', 'Large fruit'), ('Presidential', 'Presidential'), ('Small fruit', 'Small fruit')], max_length=200)),
                ('drink_amenity', models.CharField(choices=[('Negroni', 'Negroni'), ('Water', 'Water'), ('Red wine', 'Red wine'), ('White wine', 'White wine'), ('Champagne', 'Champagne')], max_length=200)),
                ('dessert_amenity', models.CharField(choices=[('Arab amenity', 'Arab amenity'), ('Macaroons 4pcs', 'Macaroons 4pcs'), ('Maamul', 'Maamul'), ('Baklava', 'Baklava'), ('Chocolate truffle', 'Chocolate truffle'), ('Macaroons 8pcs', 'Macaroons 8pcs')], default=None, max_length=200)),
                ('birthday_amenity', models.CharField(choices=[('Congartulations', 'Congratulations'), ('Happy Aniversary', 'Happy Amiversary'), ('Happy Birthday', 'Happy Birthday')], default=None, max_length=200)),
            ],
        ),
    ]
