# Generated by Django 4.0.4 on 2022-05-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputamenity',
            name='birthday_amenity',
            field=models.CharField(choices=[('Congartulations', 'Congratulations'), ('Happy Birthday', 'Happy Birthday'), ('Happy Aniversary', 'Happy Amiversary')], max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='dessert_amenity',
            field=models.CharField(choices=[('Chocolate truffle', 'Chocolate truffle'), ('Macaroons 4pcs', 'Macaroons 4pcs'), ('Macaroons 8pcs', 'Macaroons 8pcs'), ('Baklava', 'Baklava'), ('Maamul', 'Maamul'), ('Arab amenity', 'Arab amenity')], max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='drink_amenity',
            field=models.CharField(choices=[('Red wine', 'Red wine'), ('Champagne', 'Champagne'), ('Water', 'Water'), ('Negroni', 'Negroni'), ('White wine', 'White wine')], max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='fruit_amenity',
            field=models.CharField(choices=[('Small fruit', 'Small fruit'), ('Large fruit', 'Large fruit'), ('Midium fruit', 'Midium fruit'), ('Presidential', 'Presidential')], max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='guests_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='returns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='room_allocation',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='vip_level',
            field=models.IntegerField(default=0),
        ),
    ]
