# Generated by Django 4.0.4 on 2022-09-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_alter_inputamenity_birthday_amenity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputamenity',
            name='num_of_dessert',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='inputamenity',
            name='num_of_drink',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='inputamenity',
            name='num_of_fruit',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='birthday_amenity',
            field=models.CharField(blank=True, choices=[('Congartulations', 'Congratulations'), ('Happy Aniversary', 'Happy Amiversary'), ('Happy Birthday', 'Happy Birthday')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='dessert_amenity',
            field=models.CharField(blank=True, choices=[('Maamul', 'Maamul'), ('Arab amenity', 'Arab amenity'), ('Macaroons 4pcs', 'Macaroons 4pcs'), ('Chocolate truffle', 'Chocolate truffle'), ('Baklava', 'Baklava'), ('Macaroons 8pcs', 'Macaroons 8pcs')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='drink_amenity',
            field=models.CharField(blank=True, choices=[('White wine', 'White wine'), ('Red wine', 'Red wine'), ('Negroni', 'Negroni'), ('Water', 'Water'), ('Champagne', 'Champagne')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='fruit_amenity',
            field=models.CharField(blank=True, choices=[('Small fruit', 'Small fruit'), ('Presidential', 'Presidential'), ('Large fruit', 'Large fruit'), ('Midium fruit', 'Midium fruit')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='month',
            field=models.CharField(choices=[('Octomber', 'Octomber'), ('June', 'June'), ('July', 'July'), ('December', 'December'), ('March', 'March'), ('February', 'February'), ('August', 'August'), ('April', 'April'), ('January', 'January'), ('May', 'May'), ('September', 'September')], max_length=300),
        ),
        migrations.AlterField(
            model_name='longstay',
            name='amenity',
            field=models.CharField(choices=[('Flapjack', 'Flapjack'), ('Madleines', 'Madleines'), ('Macaroons', 'Macaroons'), ('Florentine', 'Florebntine'), ('Lemon cake', 'Lemon cake'), ('Pistachio Finnacier', 'Pistachio Finnacier')], max_length=200),
        ),
        migrations.AlterField(
            model_name='longstay',
            name='drink_amenity',
            field=models.CharField(blank=True, choices=[('White wine', 'White wine'), ('Red wine', 'Red wine'), ('Negroni', 'Negroni'), ('Water', 'Water'), ('Champagne', 'Champagne')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='longstay',
            name='month',
            field=models.CharField(choices=[('Octomber', 'Octomber'), ('June', 'June'), ('July', 'July'), ('December', 'December'), ('March', 'March'), ('February', 'February'), ('August', 'August'), ('April', 'April'), ('January', 'January'), ('May', 'May'), ('September', 'September')], max_length=300),
        ),
    ]
