# Generated by Django 4.0.4 on 2022-05-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_alter_inputamenity_birthday_amenity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputamenity',
            name='birthday_amenity',
            field=models.CharField(choices=[('Happy Aniversary', 'Happy Amiversary'), ('Congartulations', 'Congratulations'), ('Happy Birthday', 'Happy Birthday')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='dessert_amenity',
            field=models.CharField(choices=[('Maamul', 'Maamul'), ('Macaroons 8pcs', 'Macaroons 8pcs'), ('Baklava', 'Baklava'), ('Chocolate truffle', 'Chocolate truffle'), ('Macaroons 4pcs', 'Macaroons 4pcs'), ('Arab amenity', 'Arab amenity')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='drink_amenity',
            field=models.CharField(choices=[('Red wine', 'Red wine'), ('Water', 'Water'), ('Negroni', 'Negroni'), ('White wine', 'White wine'), ('Champagne', 'Champagne')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='fruit_amenity',
            field=models.CharField(choices=[('Large fruit', 'Large fruit'), ('Presidential', 'Presidential'), ('Small fruit', 'Small fruit'), ('Midium fruit', 'Midium fruit')], default='None', max_length=200),
        ),
    ]
