# Generated by Django 4.0.4 on 2022-05-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_alter_inputamenity_birthday_amenity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputamenity',
            name='birthday_amenity',
            field=models.CharField(choices=[('Happy Aniversary', 'Happy Amiversary'), ('Congartulations', 'Congratulations'), ('Happy Birthday', 'Happy Birthday')], default='empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='dessert_amenity',
            field=models.CharField(choices=[('Macaroons 4pcs', 'Macaroons 4pcs'), ('Baklava', 'Baklava'), ('Macaroons 8pcs', 'Macaroons 8pcs'), ('Maamul', 'Maamul'), ('Chocolate truffle', 'Chocolate truffle'), ('Arab amenity', 'Arab amenity')], default='empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='drink_amenity',
            field=models.CharField(choices=[('Champagne', 'Champagne'), ('White wine', 'White wine'), ('Water', 'Water'), ('Negroni', 'Negroni'), ('Red wine', 'Red wine')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='fruit_amenity',
            field=models.CharField(choices=[('Large fruit', 'Large fruit'), ('Small fruit', 'Small fruit'), ('Midium fruit', 'Midium fruit'), ('Presidential', 'Presidential')], default='None', max_length=200),
        ),
    ]
