# Generated by Django 4.0.4 on 2022-12-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_alter_inputamenity_birthday_amenity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputamenity',
            name='checkout_date',
            field=models.CharField(default='18/12/2022', max_length=100),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='birthday_amenity',
            field=models.CharField(blank=True, choices=[('Congartulations', 'Congratulations'), ('Happy Aniversary', 'Happy Amiversary'), ('Happy Birthday', 'Happy Birthday')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='dessert_amenity',
            field=models.CharField(blank=True, choices=[('Macaroons 4pcs', 'Macaroons 4pcs'), ('Maamul', 'Maamul'), ('Baklava', 'Baklava'), ('Macaroons 8pcs', 'Macaroons 8pcs'), ('Arab amenity', 'Arab amenity'), ('Chocolate truffle', 'Chocolate truffle')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='drink_amenity',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Champagne', 'Champagne'), ('White wine', 'White wine'), ('Red wine', 'Red wine'), ('Negroni', 'Negroni')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='fruit_amenity',
            field=models.CharField(blank=True, choices=[('Midium fruit', 'Midium fruit'), ('Large fruit', 'Large fruit'), ('Small fruit', 'Small fruit'), ('Presidential', 'Presidential')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='month',
            field=models.CharField(choices=[('Octomber', 'Octomber'), ('July', 'July'), ('April', 'April'), ('February', 'February'), ('December', 'December'), ('August', 'August'), ('November', 'November'), ('March', 'March'), ('June', 'June'), ('January', 'January'), ('September', 'September'), ('May', 'May')], max_length=300),
        ),
        migrations.AlterField(
            model_name='longstay',
            name='amenity',
            field=models.CharField(choices=[('Madleines', 'Madleines'), ('Flapjack', 'Flapjack'), ('Pistachio Finnacier', 'Pistachio Finnacier'), ('Florentine', 'Florebntine'), ('Lemon cake', 'Lemon cake'), ('Macaroons', 'Macaroons')], max_length=200),
        ),
        migrations.AlterField(
            model_name='longstay',
            name='drink_amenity',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Champagne', 'Champagne'), ('White wine', 'White wine'), ('Red wine', 'Red wine'), ('Negroni', 'Negroni')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='longstay',
            name='month',
            field=models.CharField(choices=[('Octomber', 'Octomber'), ('July', 'July'), ('April', 'April'), ('February', 'February'), ('December', 'December'), ('August', 'August'), ('November', 'November'), ('March', 'March'), ('June', 'June'), ('January', 'January'), ('September', 'September'), ('May', 'May')], max_length=300),
        ),
    ]
