# Generated by Django 4.0.4 on 2022-05-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_alter_inputamenity_birthday_amenity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputamenity',
            name='birthday_amenity',
            field=models.CharField(choices=[('Congartulations', 'Congratulations'), ('Happy Birthday', 'Happy Birthday'), ('Happy Aniversary', 'Happy Amiversary')], default='empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='dessert_amenity',
            field=models.CharField(choices=[('Maamul', 'Maamul'), ('Baklava', 'Baklava'), ('Macaroons 4pcs', 'Macaroons 4pcs'), ('Arab amenity', 'Arab amenity'), ('Chocolate truffle', 'Chocolate truffle'), ('Macaroons 8pcs', 'Macaroons 8pcs')], default='empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='drink_amenity',
            field=models.CharField(choices=[('Negroni', 'Negroni'), ('Red wine', 'Red wine'), ('Champagne', 'Champagne'), ('Water', 'Water'), ('White wine', 'White wine')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='fruit_amenity',
            field=models.CharField(choices=[('Presidential', 'Presidential'), ('Small fruit', 'Small fruit'), ('Large fruit', 'Large fruit'), ('Midium fruit', 'Midium fruit')], default='None', max_length=200),
        ),
    ]
