# Generated by Django 4.0.4 on 2022-05-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_alter_inputamenity_birthday_amenity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputamenity',
            name='birthday_amenity',
            field=models.CharField(choices=[('Congartulations', 'Congratulations'), ('Happy Aniversary', 'Happy Amiversary'), ('Happy Birthday', 'Happy Birthday')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='dessert_amenity',
            field=models.CharField(choices=[('Baklava', 'Baklava'), ('Arab amenity', 'Arab amenity'), ('Macaroons 8pcs', 'Macaroons 8pcs'), ('Chocolate truffle', 'Chocolate truffle'), ('Maamul', 'Maamul'), ('Macaroons 4pcs', 'Macaroons 4pcs')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='drink_amenity',
            field=models.CharField(choices=[('Negroni', 'Negroni'), ('Water', 'Water'), ('Champagne', 'Champagne'), ('White wine', 'White wine'), ('Red wine', 'Red wine')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='fruit_amenity',
            field=models.CharField(choices=[('Small fruit', 'Small fruit'), ('Midium fruit', 'Midium fruit'), ('Large fruit', 'Large fruit'), ('Presidential', 'Presidential')], default='None', max_length=200),
        ),
    ]
