# Generated by Django 4.0.4 on 2022-05-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_alter_inputamenity_birthday_amenity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputamenity',
            name='birthday_amenity',
            field=models.CharField(blank=True, choices=[('Congartulations', 'Congratulations'), ('Happy Aniversary', 'Happy Amiversary'), ('Happy Birthday', 'Happy Birthday')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='dessert_amenity',
            field=models.CharField(blank=True, choices=[('Macaroons 8pcs', 'Macaroons 8pcs'), ('Maamul', 'Maamul'), ('Macaroons 4pcs', 'Macaroons 4pcs'), ('Arab amenity', 'Arab amenity'), ('Baklava', 'Baklava'), ('Chocolate truffle', 'Chocolate truffle')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='drink_amenity',
            field=models.CharField(blank=True, choices=[('Champagne', 'Champagne'), ('Red wine', 'Red wine'), ('Negroni', 'Negroni'), ('Water', 'Water'), ('White wine', 'White wine')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='fruit_amenity',
            field=models.CharField(blank=True, choices=[('Midium fruit', 'Midium fruit'), ('Large fruit', 'Large fruit'), ('Small fruit', 'Small fruit'), ('Presidential', 'Presidential')], max_length=200, null=True),
        ),
    ]
