# Generated by Django 4.0.4 on 2022-05-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calc', '0011_delete_inputamenity'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputAmenity',
            fields=[
                ('big_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('membership', models.CharField(max_length=400)),
                ('returns', models.IntegerField(default=0)),
                ('vip_level', models.IntegerField(default=0)),
                ('guests_count', models.IntegerField(default=1)),
                ('room_allocation', models.IntegerField(default=100)),
                ('fruit_amenity', models.CharField(blank=True, choices=[('Midium fruit', 'Midium fruit'), ('Small fruit', 'Small fruit'), ('Large fruit', 'Large fruit'), ('Presidential', 'Presidential')], max_length=200, null=True)),
                ('drink_amenity', models.CharField(blank=True, choices=[('Negroni', 'Negroni'), ('Water', 'Water'), ('White wine', 'White wine'), ('Champagne', 'Champagne'), ('Red wine', 'Red wine')], max_length=200, null=True)),
                ('dessert_amenity', models.CharField(blank=True, choices=[('Maamul', 'Maamul'), ('Baklava', 'Baklava'), ('Arab amenity', 'Arab amenity'), ('Chocolate truffle', 'Chocolate truffle'), ('Macaroons 8pcs', 'Macaroons 8pcs'), ('Macaroons 4pcs', 'Macaroons 4pcs')], max_length=200, null=True)),
                ('birthday_amenity', models.CharField(blank=True, choices=[('Happy Aniversary', 'Happy Amiversary'), ('Happy Birthday', 'Happy Birthday'), ('Congartulations', 'Congratulations')], max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
