# Generated by Django 4.0.4 on 2022-06-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputamenity',
            name='arrival_date',
            field=models.DateField(default='2022-01-01'),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='birthday_amenity',
            field=models.CharField(blank=True, choices=[('Congartulations', 'Congratulations'), ('Happy Aniversary', 'Happy Amiversary'), ('Happy Birthday', 'Happy Birthday')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='dessert_amenity',
            field=models.CharField(blank=True, choices=[('Chocolate truffle', 'Chocolate truffle'), ('Macaroons 4pcs', 'Macaroons 4pcs'), ('Macaroons 8pcs', 'Macaroons 8pcs'), ('Arab amenity', 'Arab amenity'), ('Maamul', 'Maamul'), ('Baklava', 'Baklava')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='drink_amenity',
            field=models.CharField(blank=True, choices=[('Red wine', 'Red wine'), ('Champagne', 'Champagne'), ('Water', 'Water'), ('Negroni', 'Negroni'), ('White wine', 'White wine')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='fruit_amenity',
            field=models.CharField(blank=True, choices=[('Presidential', 'Presidential'), ('Small fruit', 'Small fruit'), ('Large fruit', 'Large fruit'), ('Midium fruit', 'Midium fruit')], max_length=200, null=True),
        ),
    ]
