# Generated by Django 4.0.4 on 2022-06-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_inputamenity_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputamenity',
            name='arrival_date',
            field=models.CharField(default='2022-01-01', max_length=100),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='birthday_amenity',
            field=models.CharField(blank=True, choices=[('Happy Birthday', 'Happy Birthday'), ('Happy Aniversary', 'Happy Amiversary'), ('Congartulations', 'Congratulations')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='dessert_amenity',
            field=models.CharField(blank=True, choices=[('Arab amenity', 'Arab amenity'), ('Chocolate truffle', 'Chocolate truffle'), ('Maamul', 'Maamul'), ('Macaroons 4pcs', 'Macaroons 4pcs'), ('Macaroons 8pcs', 'Macaroons 8pcs'), ('Baklava', 'Baklava')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='drink_amenity',
            field=models.CharField(blank=True, choices=[('Champagne', 'Champagne'), ('White wine', 'White wine'), ('Negroni', 'Negroni'), ('Water', 'Water'), ('Red wine', 'Red wine')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='fruit_amenity',
            field=models.CharField(blank=True, choices=[('Large fruit', 'Large fruit'), ('Small fruit', 'Small fruit'), ('Presidential', 'Presidential'), ('Midium fruit', 'Midium fruit')], max_length=200, null=True),
        ),
    ]
