# Generated by Django 4.0.4 on 2022-06-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_alter_inputamenity_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputamenity',
            name='dessert_amenity',
            field=models.CharField(blank=True, choices=[('Baklava', 'Baklava'), ('Macaroons 4pcs', 'Macaroons 4pcs'), ('Arab amenity', 'Arab amenity'), ('Macaroons 8pcs', 'Macaroons 8pcs'), ('Maamul', 'Maamul'), ('Chocolate truffle', 'Chocolate truffle')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='drink_amenity',
            field=models.CharField(blank=True, choices=[('Negroni', 'Negroni'), ('Champagne', 'Champagne'), ('Water', 'Water'), ('White wine', 'White wine'), ('Red wine', 'Red wine')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='fruit_amenity',
            field=models.CharField(blank=True, choices=[('Midium fruit', 'Midium fruit'), ('Small fruit', 'Small fruit'), ('Large fruit', 'Large fruit'), ('Presidential', 'Presidential')], max_length=200, null=True),
        ),
    ]
