# Generated by Django 4.0.4 on 2022-06-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_alter_inputamenity_dessert_amenity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputamenity',
            name='birthday_amenity',
            field=models.CharField(blank=True, choices=[('Congartulations', 'Congratulations'), ('Happy Birthday', 'Happy Birthday'), ('Happy Aniversary', 'Happy Amiversary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='dessert_amenity',
            field=models.CharField(blank=True, choices=[('Chocolate truffle', 'Chocolate truffle'), ('Arab amenity', 'Arab amenity'), ('Macaroons 4pcs', 'Macaroons 4pcs'), ('Maamul', 'Maamul'), ('Baklava', 'Baklava'), ('Macaroons 8pcs', 'Macaroons 8pcs')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='drink_amenity',
            field=models.CharField(blank=True, choices=[('Champagne', 'Champagne'), ('Water', 'Water'), ('Red wine', 'Red wine'), ('Negroni', 'Negroni'), ('White wine', 'White wine')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputamenity',
            name='fruit_amenity',
            field=models.CharField(blank=True, choices=[('Large fruit', 'Large fruit'), ('Small fruit', 'Small fruit'), ('Midium fruit', 'Midium fruit'), ('Presidential', 'Presidential')], max_length=200, null=True),
        ),
    ]
